---

pull_request_rules:
  - name: automatic merge with approved review
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - status-success=OSIO workload / Build workload container (pull_request)
      - status-success=Workload generator / Lint & test (pull_request)
      - status-success=Workload generator / Build generator container (pull_request)
    actions:
      merge:
        method: merge
        strict: true

  - name: automatic merge PRs by JohnStrunk
    conditions:
      - "author=JohnStrunk"
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - status-success=OSIO workload / Build workload container (pull_request)
      - status-success=Workload generator / Lint & test (pull_request)
      - status-success=Workload generator / Build generator container (pull_request)
    actions:
      merge:
        method: merge
        strict: true
