---

dist: xenial
addons:
  apt:
    packages:
      - realpath
      - ruby
      - shellcheck
language: python
python: 3.7
install:
  - travis_retry gem install asciidoctor mdl
  - travis_retry pip install yamllint tox
script:
  - tox -v
