---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ template "ocs-monkey-generator.fullname" . }}'
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
