---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ template "ocs-monkey-generator.fullname" . }}'
spec:
  storageClassName: {{ .Values.logPVCClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
